name: CI/CD pipeline

on: 
  workflow_dispatch: # Only runs manually if you trigger it

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder step
        run: echo "This is an empty pipeline. Nothing runs on push or PR."